version: '3'
services:
  mariadb:
    image: mariadb:10.4.7 # doc: https://hub.docker.com/_/mariadb
    command: mysqld --character-set-server=utf8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./mysql.conf.d:/etc/mysql/conf.d
  # mysql:
  #   image: mysql:8.0.17 # doc: https://hub.docker.com/_/mysql
  #   command: mysqld --character-set-server=utf8
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #     - ./mysql.conf.d:/etc/mysql/conf.d
  postgres:
    image: postgres:11.5 # doc: https://hub.docker.com/_/postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  redis:
    image: redis:5.0.5  # doc: https://hub.docker.com/_/redis
    ports:
      - 6379:6379
